services:
  Alterway\Bundle\RestProblemBundle\EventListener\ProblemListener:
    arguments: ['@annotation_reader']
    tags:
      - { name: kernel.event_listener, event: kernel.view, method: onKernelView }

  Alterway\Bundle\RestProblemBundle\EventListener\ExceptionListener:
    arguments: ["%kernel.debug%"]
    calls:
      - [setLogger, ['@?logger']]
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }